version: '3.7'
services:
  next-app:
    image: node:12
    command: sh -c 'npm install && npm run dev'
    working_dir: /app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      PORT: "8081"
  postgres:
    image: postgres:11
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "5432"
    environment:
      POSTGRES_PASSWORD: postgrespassword
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  graphql-engine:
    image: hasura/graphql-engine:v1.2.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase-data:/metabase-data
    depends_on:
      - postgres
volumes:
  db_data: